# Generated by Django 4.1.7 on 2023-04-04 22:39

from django.db import migrations, models
import eshopping.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0003_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=eshopping.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=eshopping.models.user_directory_path_product_image),
        ),
    ]
