# Generated by Django 4.1.7 on 2023-04-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0005_placedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
