# Generated by Django 4.1.7 on 2023-04-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0008_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='paid',
        ),
        migrations.AddField(
            model_name='placedorder',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eshopping.orderstatus'),
            preserve_default=False,
        ),
    ]
