# Generated by Django 4.1.7 on 2023-04-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0010_alter_orderstatus_status_alter_placedorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
