# Generated by Django 4.1.7 on 2023-04-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0013_alter_stock_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_check', to='eshopping.item', unique=True),
        ),
    ]
