# Generated by Django 4.1.7 on 2023-04-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0014_alter_stock_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hot_status',
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
