# Generated by Django 4.1.7 on 2023-04-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0015_remove_item_hot_status_item_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
