# Generated by Django 4.1.7 on 2023-04-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0016_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
