# Generated by Django 4.1.7 on 2023-04-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0018_alter_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
