# Generated by Django 4.1.7 on 2023-04-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0019_alter_placedorder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='have_order', to='eshopping.item'),
        ),
    ]
