# Generated by Django 4.1.7 on 2023-04-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0020_alter_placedorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
