# Generated by Django 4.1.7 on 2023-03-27 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_post_liked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_user',
            field=models.ManyToManyField(blank=True, related_name='liked_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
