# Generated by Django 4.1.7 on 2023-03-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_post_liked_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
