# Generated by Django 4.1.7 on 2023-02-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_list_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_time',
        ),
        migrations.RemoveField(
            model_name='list',
            name='add_time',
        ),
    ]
