# Generated by Django 4.1.7 on 2023-02-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_bid_bid_time_remove_list_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='temp',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
