# Generated by Django 4.1.7 on 2023-02-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='temp',
            new_name='buyer_username',
        ),
    ]
