# Generated by Django 4.1.7 on 2023-02-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_temp_bid_buyer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='buyer_username',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
